server:
  port: 8000

spring:
  application:
    name: gateway
  config: #Configuracion del servidor de configuracion
    import: optional:configserver:http://localhost:8888

eureka: #Cliente Eureka configuracion
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka