server:
  port: 8001

spring:
  application:
    name: foros
  config: #Configuracion del servidor de configuracion
    import: optional:configserver:http://localhost:8888
  datasource: #Configuracion de la base de datos y jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fororoms-foros #Crear manualmente BD fororoms-foros
    username: root
    password:
  flyway:  #Configuracion de Flyway
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka: #Cliente Eureka configuracion
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc: #Configuracion de Swagger
  swagger-ui:
    path: /swagger/swagger-ui.html

logging:
  file-name: logs/application.log
  level:
    root: INFO
    org.springframework: INFO
    org.flywaydb: DEBUG

# Configuracion de seguridad de la aplicacion
security: #Configuracion de seguridad de la aplicacion
  jwt:
    key:
      private: a7b1e437eb8db7ba1801ea13b7c329ed07c0579db9b240f4d9bc6114469aef43
    user:
      generator: OAUTH0JWT-BACKEND
