server:
  port: 8002

spring:
  application:
    name: usuarios
  config: #Configuracion del servidor de configuracion
    import: optional:configserver:http://localhost:8888
  security: #TODO Configuracion de seguridad (PROVISIONAl!)
    user:
      name: admin
      password: admin
  datasource: #Configuracion de la base de datos y jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fororoms-usuarios #Crear BD fororoms-usuarios
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka: #Cliente Eureka configuracion
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

security: #Configuracion de seguridad de la aplicacion
  jwt:
    key:
      private: a7b1e437eb8db7ba1801ea13b7c329ed07c0579db9b240f4d9bc6114469aef43
    user:
      generator: OAUTH0JWT-BACKEND

